
[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config", "portaudio", "ffmpeg"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[start]
cmd = "python server.py"

